FROM ruby:2.6.3-alpine
ENV BUILD_PACKAGES ruby-dev
RUN apk update && apk upgrade 
RUN apk add nodejs
RUN apk add --no-cache build-base
RUN apk add sqlite-dev
WORKDIR /app
ADD Gemfile* /app/
RUN bundle install
ADD . /app/
ARG AWS_ACCESS_KEY_ID
ARG AWS_REGION
ARG AWS_SECRET_ACCESS_KEY
ARG RAILS_ENV
ARG RAILS_SERVE_STATIC_FILES
ARG SECRET_KEY_BASE
ARG RSVP_CODE
ARG EMAIL_ADDRESS
ARG EMAIL_PASSWORD
ARG UBER_TOKEN
ARG GMAPS_TOKEN
ARG GOOGLE_DRIVE_SERVICE_ACCOUNT
ARG BONGSKY_UPLOADS_FOLDER_NAME
ENV AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
ENV AWS_REGION=$AWS_REGION
ENV AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
ENV RAILS_ENV=$RAILS_ENV
ENV RAILS_SERVE_STATIC_FILES=$RAILS_SERVE_STATIC_FILES
ENV SECRET_KEY_BASE=$SECRET_KEY_BASE
ENV RSVP_CODE=$RSVP_CODE
ENV EMAIL_ADDRESS=$EMAIL_ADDRESS
ENV EMAIL_PASSWORD=$EMAIL_PASSWORD
ENV UBER_TOKEN=$UBER_TOKEN
ENV GMAPS_TOKEN=$GMAPS_TOKEN
ENV GOOGLE_DRIVE_SERVICE_ACCOUNT=$GOOGLE_DRIVE_SERVICE_ACCOUNT
ENV BONGSKY_UPLOADS_FOLDER_NAME=$BONGSKY_UPLOADS_FOLDER_NAME
RUN rake db:migrate
RUN rake assets:precompile RAILS_ENV=production
RUN chmod +x bin/rails
ENTRYPOINT ["bin/rails", "server", "-e production"]
